"ackerfuchsschwanz": 0
"ackerkrummhals": 1
"ackersenf": 2
"gemeiner hohlzahn": 3
"schlitzblättriger storchschnabel": 4
"windenknöterich": 5
"winterraps": 6
"klettenlabkraut": 7
"wiesenstorchschnabel": 8
"echter vogelknöterich": 9
"wiesenknöterich": 10
"große klette": 11
"hühnerhirse": 12
"krauser ampfer": 13
"ruprechtskraut": 14
"rotklee": 15
"gemeiner rainkohl": 16
"kornblume": 17
"vogelmiere": 18