"ackerfuchsschwanz": a. myosuroides
"ackerkrummhals": a. arvensis
"ackersenf": s. arvensis
"gemeiner hohlzahn": g. tetrahit
"schlitzblättriger storchschnabel": g. dissectum
"windenknöterich": f. convolvulus
"winterraps": b. napus
"klettenlabkraut": g. aparine
"wiesenstorchschnabel": g. pratense
"echter vogelknöterich": p. aviculare
"wiesenknöterich": b. officinalis
"große klette": a. lappa
"hühnerhirse": e. crus-galli
"krauser ampfer": r. crispus
"ruprechtskraut": g. robertianum
"rotklee": t. pratense
"gemeiner rainkohl": l. communis
"kornblume": c. cyanus
"vogelmiere": s. media